export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_NOTIFICATION = 'SIGNUP_NOTIFICATION';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
