export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_NOTIFICATION = 'SIGNUP_NOTIFICATION';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER = 'GET_USER';

export const GET_USER_TWEETS = 'GET_USER_TWEETS';


export const SEND_TWEET_REQUEST = 'SEND_TWEET_REQUEST';
export const SEND_TWEET_SUCCESS = 'SEND_TWEET_SUCCESS';
export const SEND_TWEET_FAIL = 'SEND_TWEET_FAIL';

export const UPDATE_TWEETS = 'UPDATE_TWEETS';
export const TOGGLE_EDIT_TWEET = 'TOGGLE_EDIT_TWEET';
export const ADD_DETAILED_TWEET = 'ADD_DETAILED_TWEET';
export const RESET_DETAILED_TWEET = 'RESET_DETAILED_TWEET';

export const SUBMIT_SEARCH_REQUEST = 'SUBMIT_SEARCH_REQUEST';
export const SUBMIT_SEARCH_SUCCESS = 'SUBMIT_SEARCH_SUCCESS';

export const UPDATE_SEARCH = 'UPDATE_SEARCH';
